# Generated by Django 4.2.7 on 2025-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь.', related_name='worker', related_query_name='worker', to='auth.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Разрешения, предоставленные пользователю.', related_name='worker', related_query_name='worker', to='auth.permission', verbose_name='Разрешения пользователя'),
        ),
    ]
