# Generated by Django 4.2.7 on 2025-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_groups_alter_worker_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='grade',
            field=models.CharField(choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior'), ('TEAMLEAD', 'Teamlead')], default='JUNIOR', max_length=50, verbose_name='Грейд'),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_exp',
            field=models.IntegerField(default=0, verbose_name='Опыт работы'),
        ),
    ]
