# Generated by Django 4.2.7 on 2025-06-01 07:24

from django.db import migrations, models
import django.db.models.deletion
import tasks.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(max_length=200, verbose_name='Описание задачи')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('price', models.IntegerField(verbose_name='Стоимость проекта')),
                ('complexity', models.IntegerField(verbose_name='Сложность проекта')),
                ('link', models.TextField(blank=True, max_length=200, null=True, verbose_name='Дополнительные ссылки')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Статус выполнения задачи')),
                ('color_tag', models.CharField(blank=True, help_text='Цвет в формате #000000', max_length=7, null=True, verbose_name='Цветовой тэг (HEX)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
            },
        ),
        migrations.CreateModel(
            name='WorkDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Направление')),
                ('tech_stack', models.CharField(max_length=300, verbose_name='Стек технологий')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Направление задачи',
                'verbose_name_plural': 'Направление задач',
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tasks.utils.upload_to_path, validators=[tasks.utils.validate_file_extension], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='Задача')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.workdirection', verbose_name='Направление работы'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskstatus', verbose_name='Статус задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.team', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ManyToManyField(to='workers.worker', verbose_name='Исполнители'),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название подзадачи')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание подзадачи')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Подзадача')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title', 'direction', 'deadline', 'status'], name='tasks_task_title_db0c8a_idx'),
        ),
    ]
