# Generated by Django 4.2.7 on 2025-06-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='color_tag',
        ),
    ]
