# Generated by Django 4.2.7 on 2025-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskstatus_color_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdirection',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Стек технологий'),
        ),
    ]
