# Generated by Django 4.2.7 on 2025-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название команды')),
                ('type', models.CharField(max_length=100, verbose_name='Тип команды')),
                ('members', models.IntegerField(default=0, verbose_name='Количество участников')),
                ('active_projects', models.IntegerField(default=0, verbose_name='Активные проекты')),
                ('skills', models.JSONField(default=list, verbose_name='Навыки')),
                ('availability', models.IntegerField(default=100, verbose_name='Доступность (%)')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name'],
            },
        ),
    ]
